# Database Configuration
# PostgreSQL connection properties for Summative Project

db.url=jdbc:postgresql://localhost/ensf380project
db.username=oop
db.password=ucalgary
db.driver=org.postgresql.Driver
